//! Exhaustive schema-to-status manifest for every canonical `config.toml`
//! path in scope for issue #1462.
//!
//! This manifest is the single source of truth PR 1 of the #1462 stack
//! derives static validation from: for every canonical TOML path it records
//! whether that path is [`WiringStatus::Wired`], [`WiringStatus::Partial`],
//! [`WiringStatus::Unwired`], or [`WiringStatus::Rejected`] today, which
//! implementation PR in #1462 (if any) completes the runtime path, why, and
//! what a downstream validator should do about it
//! ([`WiringBehavior`]).
//!
//! `crates/mesh-llm-config/src/website_docs_parity.rs` asserts that this
//! manifest agrees, path for path, with the `Status` column of
//! `website/src/docs/pages/config-reference.md` and the `Wiring status`
//! column of `docs/skippy/CONFIGURATION.md`. `crates/mesh-llm-config/src/wiring_validation.rs`
//! derives `ConfigDiagnostic`s from [`WiringBehavior`] so `mesh-llm config
//! validate` agrees with real runtime support instead of drifting from it.

/// The wiring status of one canonical config path, matching the `Status`
/// column used across the public docs (`website/src/docs/pages/config-reference.md`)
/// and the internal matrix (`docs/skippy/CONFIGURATION.md`).
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum WiringStatus {
    Wired,
    Partial,
    Unwired,
    Rejected,
}

impl WiringStatus {
    /// Render the lowercase token used by both status-matrix documents.
    pub const fn as_matrix_token(self) -> &'static str {
        match self {
            Self::Wired => "wired",
            Self::Partial => "partial",
            Self::Unwired => "unwired",
            Self::Rejected => "rejected",
        }
    }
}

/// What a static validator should do about a path's current wiring gap.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum WiringBehavior {
    /// The field is fully wired (or its validator behavior is owned
    /// elsewhere already); `mesh-llm config validate` emits no manifest-
    /// driven diagnostic for it.
    None,
    /// The field is explicitly rejected; belongs to another subsystem or
    /// is not implemented at all. Emits a `RejectedField` error.
    Rejected,
    /// The field passes static validation today but currently causes a
    /// hard failure downstream (at model load or request resolution).
    /// `mesh-llm config validate` should surface this as an error instead
    /// of letting the operator discover it at resolve time.
    BailsDownstream,
    /// The field passes static validation and resolution, but no runtime
    /// consumer reads the resolved value: it is a silent no-op today.
    /// `mesh-llm config validate` should warn.
    SilentNoOp,
}

/// One row of the exhaustive schema-to-status manifest.
#[derive(Clone, Copy, Debug)]
pub struct WiringEntry {
    /// The canonical, unprefixed key path (e.g. `model_fit.kv_offload`),
    /// matching the short form the website configuration reference and the
    /// internal status matrix both document once per field.
    pub path: &'static str,
    pub status: WiringStatus,
    /// The #1462 implementation PR that completes this field's runtime
    /// path, or `"n/a"` for fields with no owning PR in this stack (fully
    /// wired fields, and permanently rejected fields).
    pub owner: &'static str,
    /// Why the field has this status today; empty for `Wired` fields.
    pub reason: &'static str,
    pub behavior: WiringBehavior,
}

/// The exhaustive schema-to-status manifest: one entry per canonical
/// `config.toml` path in scope for issue #1462.
pub const WIRING_MANIFEST: &[WiringEntry] = &[
    WiringEntry {
        path: "version",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "gpu.assignment",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "gpu.parallel",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "mesh_requirements.min_node_version",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "mesh_requirements.max_node_version",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "mesh_requirements.min_protocol_version",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "mesh_requirements.max_protocol_version",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "mesh_requirements.require_release_attestation",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "mesh_requirements.release_signer_keys",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "owner_control.bind",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "owner_control.advertise_addr",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "telemetry.enabled",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "telemetry.service_name",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "telemetry.endpoint",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "telemetry.headers",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "telemetry.export_interval_secs",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "telemetry.queue_size",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "telemetry.metrics.endpoint",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "logging.audit.enabled",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "logging.audit.log_path",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "logging.audit.log_format",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "logging.audit.log_level",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "logging.audit.max_file_size_mb",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "logging.audit.max_files",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "logging.enabled",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "logging.application_state_root",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "logging.summary_line_limit",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "logging.event_buffer_size",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "logging.retention_ttl_secs",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "logging.retention_max_rows",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "logging.replay_capacity",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "logging.queue_capacity",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "logging.export_limit_bytes",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "logging.cleanup_cadence_secs",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "logging.artifact.capture_mode",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "logging.artifact.byte_limit_bytes",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "logging.artifact.aggregate_limit_bytes",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "logging.webhook.enabled",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "logging.webhook.url",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "logging.webhook.max_attempts",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "logging.webhook.timeout_secs",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "logging.webhook.dead_letter_retention_secs",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "runtime.debug",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "runtime.listen_all",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "runtime.mode",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "runtime.startup_failure_policy",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "runtime.drain_timeout_secs",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "runtime.drain_timeout_max_secs",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "runtime.activity.enabled",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "runtime.activity.idle_after_secs",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "runtime.activity.poll_interval_secs",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "runtime.activity.resume_debounce_secs",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "runtime.activity.response",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "runtime.activity.advertisement",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "runtime.reconcile_model_targets",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "runtime.reconcile_model_target_demand_upgrades",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "runtime.native_runtime.mesh_version",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "runtime.native_runtime.skippy_abi",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "runtime.native_runtime.selection",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "runtime.model_target_demand_upgrade_min_requests",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "runtime.model_target_demand_upgrade_max_age_secs",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "advanced.server.alias",
        status: WiringStatus::Unwired,
        owner: "PR8",
        reason: "Served identity, /v1/models, and routing never read it",
        behavior: WiringBehavior::SilentNoOp,
    },
    WiringEntry {
        path: "model",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "hardware.model_path",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "hardware.hf_repo",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "hardware.hf_file",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "model_fit.ctx_size",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "model_fit.batch",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "model_fit.ubatch",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "model_fit.cache_type_k",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "model_fit.cache_type_v",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "model_fit.kv_cache_policy",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "model_fit.kv_offload",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "model_fit.kv_unified",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "model_fit.cache_ram_mib",
        status: WiringStatus::Unwired,
        owner: "PR2",
        reason: "Any positive value fails at model load",
        behavior: WiringBehavior::BailsDownstream,
    },
    WiringEntry {
        path: "model_fit.cache_idle_slots",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "model_fit.prompt_cache",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "model_fit.prefix_cache.enabled",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "model_fit.prefix_cache.max_entries",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "model_fit.prefix_cache.max_bytes",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "model_fit.prefix_cache.min_tokens",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "model_fit.prefix_cache.shared_stride_tokens",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "model_fit.prefix_cache.shared_record_limit",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "model_fit.prefix_cache.payload_mode",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "model_fit.keep_tokens",
        status: WiringStatus::Unwired,
        owner: "PR2",
        reason: "Any positive value fails at model load",
        behavior: WiringBehavior::BailsDownstream,
    },
    WiringEntry {
        path: "model_fit.context_shift",
        status: WiringStatus::Unwired,
        owner: "PR2",
        reason: "auto/false pass resolution; explicit true fails at model load",
        behavior: WiringBehavior::BailsDownstream,
    },
    WiringEntry {
        path: "model_fit.swa_full",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "model_fit.checkpoint_interval",
        status: WiringStatus::Unwired,
        owner: "PR2",
        reason: "Any configured value fails at model load",
        behavior: WiringBehavior::BailsDownstream,
    },
    WiringEntry {
        path: "model_fit.checkpoint_count",
        status: WiringStatus::Unwired,
        owner: "PR2",
        reason: "Any configured value fails at model load",
        behavior: WiringBehavior::BailsDownstream,
    },
    WiringEntry {
        path: "model_fit.lookup_cache_static",
        status: WiringStatus::Unwired,
        owner: "PR2",
        reason: "Any configured value fails at model load",
        behavior: WiringBehavior::BailsDownstream,
    },
    WiringEntry {
        path: "model_fit.lookup_cache_dynamic",
        status: WiringStatus::Unwired,
        owner: "PR2",
        reason: "Any configured value fails at model load",
        behavior: WiringBehavior::BailsDownstream,
    },
    WiringEntry {
        path: "model_fit.flash_attention",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "hardware.model_runtime",
        status: WiringStatus::Unwired,
        owner: "PR3",
        reason: "No per-model runtime selector or advertised runtime-kind semantics",
        behavior: WiringBehavior::SilentNoOp,
    },
    WiringEntry {
        path: "hardware.device",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "hardware.gpu_layers",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "hardware.stage_layer_start",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "hardware.stage_layer_end",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "hardware.placement",
        status: WiringStatus::Unwired,
        owner: "PR3",
        reason: "Passes static validation, then fails at model load",
        behavior: WiringBehavior::BailsDownstream,
    },
    WiringEntry {
        path: "hardware.tensor_split",
        status: WiringStatus::Unwired,
        owner: "PR3",
        reason: "Passes static validation, then fails at model load",
        behavior: WiringBehavior::BailsDownstream,
    },
    WiringEntry {
        path: "hardware.split_mode",
        status: WiringStatus::Unwired,
        owner: "PR3",
        reason: "No resolver, bridge, or native reader",
        behavior: WiringBehavior::SilentNoOp,
    },
    WiringEntry {
        path: "hardware.main_gpu",
        status: WiringStatus::Unwired,
        owner: "PR3",
        reason: "No resolver, bridge, or native reader",
        behavior: WiringBehavior::SilentNoOp,
    },
    WiringEntry {
        path: "hardware.cpu_moe",
        status: WiringStatus::Unwired,
        owner: "PR3",
        reason: "Passes static validation, then fails at model load",
        behavior: WiringBehavior::BailsDownstream,
    },
    WiringEntry {
        path: "hardware.n_cpu_moe",
        status: WiringStatus::Unwired,
        owner: "PR3",
        reason: "Passes static validation, then fails at model load",
        behavior: WiringBehavior::BailsDownstream,
    },
    WiringEntry {
        path: "hardware.fit_target_mib",
        status: WiringStatus::Partial,
        owner: "PR3",
        reason: "Offline GPU tuner reads it; live serving placement ignores it",
        behavior: WiringBehavior::SilentNoOp,
    },
    WiringEntry {
        path: "hardware.safety_margin_gb",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "hardware.fit_context",
        status: WiringStatus::Unwired,
        owner: "PR3",
        reason: "Serving planner ignores it",
        behavior: WiringBehavior::SilentNoOp,
    },
    WiringEntry {
        path: "hardware.lora_adapters",
        status: WiringStatus::Unwired,
        owner: "PR3",
        reason: "No native LoRA load/apply path",
        behavior: WiringBehavior::SilentNoOp,
    },
    WiringEntry {
        path: "hardware.control_vectors",
        status: WiringStatus::Unwired,
        owner: "PR3",
        reason: "No native control-vector load/apply path",
        behavior: WiringBehavior::SilentNoOp,
    },
    WiringEntry {
        path: "hardware.check_tensors",
        status: WiringStatus::Unwired,
        owner: "PR3",
        reason: "No validation, resolver, or native reader",
        behavior: WiringBehavior::SilentNoOp,
    },
    WiringEntry {
        path: "hardware.mmap",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "hardware.mlock",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "hardware.direct_io",
        status: WiringStatus::Unwired,
        owner: "PR3",
        reason: "No loader support or early rejection",
        behavior: WiringBehavior::SilentNoOp,
    },
    WiringEntry {
        path: "hardware.repack",
        status: WiringStatus::Unwired,
        owner: "PR3",
        reason: "Native bridge hardcodes repack enabled and ignores TOML",
        behavior: WiringBehavior::SilentNoOp,
    },
    WiringEntry {
        path: "hardware.op_offload",
        status: WiringStatus::Unwired,
        owner: "PR3",
        reason: "No native field or consumer",
        behavior: WiringBehavior::SilentNoOp,
    },
    WiringEntry {
        path: "hardware.no_host_buffer",
        status: WiringStatus::Unwired,
        owner: "PR3",
        reason: "Closest native fields are hardcoded false",
        behavior: WiringBehavior::SilentNoOp,
    },
    WiringEntry {
        path: "hardware.warmup",
        status: WiringStatus::Unwired,
        owner: "PR3",
        reason: "No resolver or warmup-path reader",
        behavior: WiringBehavior::SilentNoOp,
    },
    WiringEntry {
        path: "throughput.parallel",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "throughput.continuous_batching",
        status: WiringStatus::Unwired,
        owner: "PR4",
        reason: "Scheduler/native execution never reads the resolved value",
        behavior: WiringBehavior::SilentNoOp,
    },
    WiringEntry {
        path: "throughput.threads",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "throughput.threads_batch",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "throughput.priority",
        status: WiringStatus::Unwired,
        owner: "PR4",
        reason: "No scheduling or OS-priority consumer",
        behavior: WiringBehavior::SilentNoOp,
    },
    WiringEntry {
        path: "throughput.poll",
        status: WiringStatus::Unwired,
        owner: "PR4",
        reason: "No native execution consumer",
        behavior: WiringBehavior::SilentNoOp,
    },
    WiringEntry {
        path: "throughput.cpu_affinity",
        status: WiringStatus::Unwired,
        owner: "PR4",
        reason: "No inference-thread affinity consumer",
        behavior: WiringBehavior::SilentNoOp,
    },
    WiringEntry {
        path: "throughput.numa",
        status: WiringStatus::Unwired,
        owner: "PR4",
        reason: "No native NUMA consumer",
        behavior: WiringBehavior::SilentNoOp,
    },
    WiringEntry {
        path: "throughput.slot_prompt_similarity",
        status: WiringStatus::Unwired,
        owner: "PR4",
        reason: "Slot/session reuse ignores it",
        behavior: WiringBehavior::SilentNoOp,
    },
    WiringEntry {
        path: "throughput.tuning_profile",
        status: WiringStatus::Partial,
        owner: "PR4",
        reason: "Expands batch, ubatch, and parallel; its continuous-batching result is dropped",
        behavior: WiringBehavior::SilentNoOp,
    },
    WiringEntry {
        path: "skippy.stage_model_path",
        status: WiringStatus::Unwired,
        owner: "PR4",
        reason: "Package materialization uses hardware/model source paths instead",
        behavior: WiringBehavior::SilentNoOp,
    },
    WiringEntry {
        path: "skippy.stage_role",
        status: WiringStatus::Unwired,
        owner: "PR4",
        reason: "Topology planner always computes the role itself",
        behavior: WiringBehavior::SilentNoOp,
    },
    WiringEntry {
        path: "skippy.stage_topology",
        status: WiringStatus::Unwired,
        owner: "PR4",
        reason: "The similarly named runtime topology is computed and unrelated to TOML",
        behavior: WiringBehavior::SilentNoOp,
    },
    WiringEntry {
        path: "skippy.binary_stage_transport",
        status: WiringStatus::Unwired,
        owner: "PR4",
        reason: "Result is dropped; binary transport is effectively unconditional",
        behavior: WiringBehavior::SilentNoOp,
    },
    WiringEntry {
        path: "skippy.lifecycle_startup_timeout_ms",
        status: WiringStatus::Unwired,
        owner: "PR4",
        reason: "Real startup timeout is hardcoded",
        behavior: WiringBehavior::SilentNoOp,
    },
    WiringEntry {
        path: "skippy.lifecycle_readiness_interval_ms",
        status: WiringStatus::Unwired,
        owner: "PR4",
        reason: "Real poll intervals are hardcoded",
        behavior: WiringBehavior::SilentNoOp,
    },
    WiringEntry {
        path: "skippy.lifecycle_health_interval_ms",
        status: WiringStatus::Unwired,
        owner: "PR4",
        reason: "No health scheduler reads it",
        behavior: WiringBehavior::SilentNoOp,
    },
    WiringEntry {
        path: "skippy.prefill_chunking",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "skippy.prefill_chunk_size",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "skippy.prefill_chunk_schedule",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "speculative.strategy",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "speculative.mode",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "speculative.draft_model",
        status: WiringStatus::Unwired,
        owner: "PR5",
        reason: "Any configured value fails during resolution",
        behavior: WiringBehavior::BailsDownstream,
    },
    WiringEntry {
        path: "speculative.draft_hf_repo",
        status: WiringStatus::Unwired,
        owner: "PR5",
        reason: "Any configured value fails during resolution",
        behavior: WiringBehavior::BailsDownstream,
    },
    WiringEntry {
        path: "speculative.draft_hf_file",
        status: WiringStatus::Unwired,
        owner: "PR5",
        reason: "Any configured value fails during resolution",
        behavior: WiringBehavior::BailsDownstream,
    },
    WiringEntry {
        path: "speculative.draft_selection_policy",
        status: WiringStatus::Unwired,
        owner: "PR5",
        reason: "Policy value never selects a draft",
        behavior: WiringBehavior::SilentNoOp,
    },
    WiringEntry {
        path: "speculative.pairing_fault",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "speculative.draft_max_tokens",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "speculative.draft_min_tokens",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "speculative.draft_acceptance_threshold",
        status: WiringStatus::Unwired,
        owner: "PR5",
        reason: "Any value above 0.0 currently fails closed during resolution",
        behavior: WiringBehavior::BailsDownstream,
    },
    WiringEntry {
        path: "speculative.draft_split_probability",
        status: WiringStatus::Unwired,
        owner: "PR5",
        reason: "Resolver fail-closed today",
        behavior: WiringBehavior::BailsDownstream,
    },
    WiringEntry {
        path: "speculative.draft_gpu_layers",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "speculative.draft_device",
        status: WiringStatus::Unwired,
        owner: "PR5",
        reason: "Any configured value fails during resolution",
        behavior: WiringBehavior::BailsDownstream,
    },
    WiringEntry {
        path: "speculative.draft_threads",
        status: WiringStatus::Unwired,
        owner: "PR5",
        reason: "Any configured value fails during resolution",
        behavior: WiringBehavior::BailsDownstream,
    },
    WiringEntry {
        path: "speculative.draft_cache_type_k",
        status: WiringStatus::Unwired,
        owner: "PR5",
        reason: "Currently rejected by the resolver",
        behavior: WiringBehavior::BailsDownstream,
    },
    WiringEntry {
        path: "speculative.draft_cache_type_v",
        status: WiringStatus::Unwired,
        owner: "PR5",
        reason: "Currently rejected by the resolver",
        behavior: WiringBehavior::BailsDownstream,
    },
    WiringEntry {
        path: "speculative.ngram_min",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "speculative.ngram_max",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "speculative.ngram_proposer",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "speculative.ngram_max_proposal_tokens",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "speculative.extension_max_tokens",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "speculative.native_mtp_reject_cooldown_tokens",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "speculative.native_mtp_suppress_cooldown_drafts",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "speculative.native_mtp_suppress_cooldown_draft_limit",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "speculative.verify_window_min_tokens",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "speculative.verify_window_max_tokens",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "speculative.verify_window_pipeline_depth",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "speculative.spec_default",
        status: WiringStatus::Partial,
        owner: "PR5",
        reason: "false/auto/unset participate in native-MTP auto selection; explicit true fails during resolution",
        behavior: WiringBehavior::SilentNoOp,
    },
    WiringEntry {
        path: "request_defaults.max_tokens",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "request_defaults.stop",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "request_defaults.temperature",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "request_defaults.top_p",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "request_defaults.top_k",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "request_defaults.min_p",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "request_defaults.typical_p",
        status: WiringStatus::Unwired,
        owner: "PR6",
        reason: "Config resolution fails; native sampler bridge lacks the field",
        behavior: WiringBehavior::BailsDownstream,
    },
    WiringEntry {
        path: "request_defaults.top_nsigma",
        status: WiringStatus::Unwired,
        owner: "PR6",
        reason: "Config resolution fails; native sampler bridge lacks the field",
        behavior: WiringBehavior::BailsDownstream,
    },
    WiringEntry {
        path: "request_defaults.dynatemp_range",
        status: WiringStatus::Unwired,
        owner: "PR6",
        reason: "Config resolution fails; native call hardcodes 0.0/1.0",
        behavior: WiringBehavior::BailsDownstream,
    },
    WiringEntry {
        path: "request_defaults.dynatemp_exponent",
        status: WiringStatus::Unwired,
        owner: "PR6",
        reason: "Config resolution fails; native call hardcodes 0.0/1.0",
        behavior: WiringBehavior::BailsDownstream,
    },
    WiringEntry {
        path: "request_defaults.repeat_penalty",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "request_defaults.repeat_last_n",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "request_defaults.presence_penalty",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "request_defaults.frequency_penalty",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "request_defaults.dry",
        status: WiringStatus::Unwired,
        owner: "PR6",
        reason: "The empty namespace parses; real DRY fields fail TOML parsing and no native DRY sampler is built",
        behavior: WiringBehavior::BailsDownstream,
    },
    WiringEntry {
        path: "request_defaults.xtc",
        status: WiringStatus::Unwired,
        owner: "PR6",
        reason: "The empty namespace parses; real XTC fields fail TOML parsing and no native XTC sampler is built",
        behavior: WiringBehavior::BailsDownstream,
    },
    WiringEntry {
        path: "request_defaults.mirostat_mode",
        status: WiringStatus::Unwired,
        owner: "PR6",
        reason: "Resolution rejects configured values",
        behavior: WiringBehavior::BailsDownstream,
    },
    WiringEntry {
        path: "request_defaults.mirostat_entropy",
        status: WiringStatus::Unwired,
        owner: "PR6",
        reason: "Resolution rejects configured values",
        behavior: WiringBehavior::BailsDownstream,
    },
    WiringEntry {
        path: "request_defaults.mirostat_learning_rate",
        status: WiringStatus::Unwired,
        owner: "PR6",
        reason: "Resolution rejects configured values",
        behavior: WiringBehavior::BailsDownstream,
    },
    WiringEntry {
        path: "request_defaults.samplers",
        status: WiringStatus::Unwired,
        owner: "PR6",
        reason: "Custom order is rejected; native chain is hardcoded",
        behavior: WiringBehavior::BailsDownstream,
    },
    WiringEntry {
        path: "request_defaults.sampler_sequence",
        status: WiringStatus::Unwired,
        owner: "PR6",
        reason: "Custom order is rejected; native chain is hardcoded",
        behavior: WiringBehavior::BailsDownstream,
    },
    WiringEntry {
        path: "request_defaults.seed",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "request_defaults.logit_bias",
        status: WiringStatus::Unwired,
        owner: "PR6",
        reason: "No native logit-bias consumer for the config default path",
        behavior: WiringBehavior::SilentNoOp,
    },
    WiringEntry {
        path: "request_defaults.ignore_eos",
        status: WiringStatus::Unwired,
        owner: "PR6",
        reason: "Resolution rejects it and the native chain has no suppression behavior",
        behavior: WiringBehavior::BailsDownstream,
    },
    WiringEntry {
        path: "request_defaults.reasoning_format",
        status: WiringStatus::Partial,
        owner: "PR6",
        reason: "Config value reaches the native call, but a request cannot override the config default",
        behavior: WiringBehavior::SilentNoOp,
    },
    WiringEntry {
        path: "request_defaults.reasoning_enabled",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "request_defaults.reasoning_budget",
        status: WiringStatus::Partial,
        owner: "PR6",
        reason: "Acts only as an enabled/disabled gate; numeric budget or effort tier is discarded",
        behavior: WiringBehavior::SilentNoOp,
    },
    WiringEntry {
        path: "request_defaults.chat_template",
        status: WiringStatus::Unwired,
        owner: "PR6",
        reason: "Config resolution rejects it; template renderer never receives it",
        behavior: WiringBehavior::BailsDownstream,
    },
    WiringEntry {
        path: "request_defaults.chat_template_file",
        status: WiringStatus::Unwired,
        owner: "PR6",
        reason: "Config resolution rejects it; template renderer never receives it",
        behavior: WiringBehavior::BailsDownstream,
    },
    WiringEntry {
        path: "request_defaults.jinja",
        status: WiringStatus::Unwired,
        owner: "PR6",
        reason: "Config resolution rejects it; template renderer never receives it",
        behavior: WiringBehavior::BailsDownstream,
    },
    WiringEntry {
        path: "request_defaults.chat_template_kwargs",
        status: WiringStatus::Partial,
        owner: "PR6",
        reason: "Request-body kwargs work, but a TOML-configured default is rejected and never merged",
        behavior: WiringBehavior::BailsDownstream,
    },
    WiringEntry {
        path: "request_defaults.skip_chat_parsing",
        status: WiringStatus::Unwired,
        owner: "PR6",
        reason: "Config resolution rejects it; frontend has no bypass",
        behavior: WiringBehavior::BailsDownstream,
    },
    WiringEntry {
        path: "request_defaults.prefill_assistant",
        status: WiringStatus::Unwired,
        owner: "PR6",
        reason: "Config resolution rejects it; no assistant-prefill path reads it",
        behavior: WiringBehavior::BailsDownstream,
    },
    WiringEntry {
        path: "request_defaults.system_prompt",
        status: WiringStatus::Unwired,
        owner: "PR6",
        reason: "Config resolution rejects it; no fallback injection exists",
        behavior: WiringBehavior::BailsDownstream,
    },
    WiringEntry {
        path: "multimodal.mmproj",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "hardware.mmproj",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "multimodal.mmproj_url",
        status: WiringStatus::Unwired,
        owner: "PR7",
        reason: "URL shape is validated; no fetch or materialization path exists",
        behavior: WiringBehavior::SilentNoOp,
    },
    WiringEntry {
        path: "multimodal.mmproj_offload",
        status: WiringStatus::Unwired,
        owner: "PR7",
        reason: "Native projector initialization always forces GPU",
        behavior: WiringBehavior::SilentNoOp,
    },
    WiringEntry {
        path: "hardware.mmproj_offload",
        status: WiringStatus::Unwired,
        owner: "PR7",
        reason: "Native projector initialization always forces GPU",
        behavior: WiringBehavior::SilentNoOp,
    },
    WiringEntry {
        path: "multimodal.image_min_tokens",
        status: WiringStatus::Unwired,
        owner: "PR7",
        reason: "Native mtmd struct supports it; Rust call site leaves library defaults",
        behavior: WiringBehavior::SilentNoOp,
    },
    WiringEntry {
        path: "multimodal.image_max_tokens",
        status: WiringStatus::Unwired,
        owner: "PR7",
        reason: "Native mtmd struct supports it; Rust call site leaves library defaults",
        behavior: WiringBehavior::SilentNoOp,
    },
    WiringEntry {
        path: "plugin.<name>.name",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "plugin.<name>.enabled",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "plugin.<name>.web_ui_enabled",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "plugin.<name>.command",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "plugin.<name>.args",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "plugin.<name>.url",
        status: WiringStatus::Partial,
        owner: "PR8",
        reason: "Injected into a spawned child environment; does not connect to an already-running remote plugin, and command stays mandatory",
        behavior: WiringBehavior::SilentNoOp,
    },
    WiringEntry {
        path: "plugin.<name>.startup.connect_timeout_secs",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "plugin.<name>.startup.init_timeout_secs",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "plugin.<name>.startup.optional",
        status: WiringStatus::Partial,
        owner: "PR8",
        reason: "Controls command-resolution fatality only; spawn, connect, and init failures do not consistently honor it",
        behavior: WiringBehavior::SilentNoOp,
    },
    WiringEntry {
        path: "plugin.<name>.startup.lazy_start",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "plugin.<name>.settings.*",
        status: WiringStatus::Wired,
        owner: "n/a",
        reason: "",
        behavior: WiringBehavior::None,
    },
    WiringEntry {
        path: "hardware.rpc_backend",
        status: WiringStatus::Rejected,
        owner: "n/a",
        reason: "The legacy RPC-backend escape hatch is explicitly unsupported by the embedded runtime; lower-layer RPC backend selection is not operator-configurable.",
        behavior: WiringBehavior::Rejected,
    },
    WiringEntry {
        path: "throughput.threads_http",
        status: WiringStatus::Rejected,
        owner: "n/a",
        reason: "Dedicated HTTP worker tuning stays a host runtime setting, not a model setting.",
        behavior: WiringBehavior::Rejected,
    },
    WiringEntry {
        path: "throughput.sleep_idle_seconds",
        status: WiringStatus::Rejected,
        owner: "n/a",
        reason: "Power-management idle sleep stays operational, outside model config.",
        behavior: WiringBehavior::Rejected,
    },
    WiringEntry {
        path: "skippy.openai_frontend_mode",
        status: WiringStatus::Rejected,
        owner: "n/a",
        reason: "Frontend surface mode belongs to deployment or service config.",
        behavior: WiringBehavior::Rejected,
    },
    WiringEntry {
        path: "request_defaults.backend_sampling",
        status: WiringStatus::Rejected,
        owner: "n/a",
        reason: "Backend-owned sampler blocks are not modeled until a real sampling toggle exists end to end.",
        behavior: WiringBehavior::Rejected,
    },
    WiringEntry {
        path: "request_defaults.adaptive",
        status: WiringStatus::Rejected,
        owner: "n/a",
        reason: "Reserved for a future adaptive sampler; only an empty object is accepted.",
        behavior: WiringBehavior::Rejected,
    },
    WiringEntry {
        path: "advanced.server.host",
        status: WiringStatus::Rejected,
        owner: "n/a",
        reason: "Listen address is deployment/service scope, not model scope.",
        behavior: WiringBehavior::Rejected,
    },
    WiringEntry {
        path: "advanced.server.port",
        status: WiringStatus::Rejected,
        owner: "n/a",
        reason: "Listen port is deployment/service scope, not model scope.",
        behavior: WiringBehavior::Rejected,
    },
    WiringEntry {
        path: "advanced.server.reuse_port",
        status: WiringStatus::Rejected,
        owner: "n/a",
        reason: "Socket tuning stays operational.",
        behavior: WiringBehavior::Rejected,
    },
    WiringEntry {
        path: "advanced.server.timeout",
        status: WiringStatus::Rejected,
        owner: "n/a",
        reason: "Timeout ownership stays operational, not model scope.",
        behavior: WiringBehavior::Rejected,
    },
    WiringEntry {
        path: "advanced.server.metrics",
        status: WiringStatus::Rejected,
        owner: "n/a",
        reason: "Metrics exposure stays operational.",
        behavior: WiringBehavior::Rejected,
    },
    WiringEntry {
        path: "advanced.server.slots",
        status: WiringStatus::Rejected,
        owner: "n/a",
        reason: "The slots debug endpoint stays operational.",
        behavior: WiringBehavior::Rejected,
    },
    WiringEntry {
        path: "advanced.server.props",
        status: WiringStatus::Rejected,
        owner: "n/a",
        reason: "The props debug endpoint stays operational.",
        behavior: WiringBehavior::Rejected,
    },
    WiringEntry {
        path: "advanced.server.api_prefix",
        status: WiringStatus::Rejected,
        owner: "n/a",
        reason: "Route prefix stays deployment-owned.",
        behavior: WiringBehavior::Rejected,
    },
    WiringEntry {
        path: "multimodal.embeddings",
        status: WiringStatus::Rejected,
        owner: "n/a",
        reason: "Embeddings is not an implemented product mode.",
        behavior: WiringBehavior::Rejected,
    },
    WiringEntry {
        path: "multimodal.reranking",
        status: WiringStatus::Rejected,
        owner: "n/a",
        reason: "Reranking is not an implemented product mode.",
        behavior: WiringBehavior::Rejected,
    },
    WiringEntry {
        path: "multimodal.pooling",
        status: WiringStatus::Rejected,
        owner: "n/a",
        reason: "Pooling is not an implemented product mode.",
        behavior: WiringBehavior::Rejected,
    },
    WiringEntry {
        path: "multimodal.vocoder",
        status: WiringStatus::Rejected,
        owner: "n/a",
        reason: "Vocoder/audio generation is not an implemented product mode.",
        behavior: WiringBehavior::Rejected,
    },
    WiringEntry {
        path: "request_defaults.grammar",
        status: WiringStatus::Rejected,
        owner: "n/a",
        reason: "Grammar constraint execution is not implemented in the embedded runtime yet.",
        behavior: WiringBehavior::Rejected,
    },
    WiringEntry {
        path: "request_defaults.json_schema",
        status: WiringStatus::Rejected,
        owner: "n/a",
        reason: "JSON-schema response shaping is not implemented in the embedded runtime yet.",
        behavior: WiringBehavior::Rejected,
    },
    WiringEntry {
        path: "request_defaults.logprobs",
        status: WiringStatus::Rejected,
        owner: "n/a",
        reason: "Logprobs response support is not implemented yet.",
        behavior: WiringBehavior::Rejected,
    },
];

/// Look up a manifest entry by its canonical short path.
pub fn wiring_entry_for_path(path: &str) -> Option<&'static WiringEntry> {
    WIRING_MANIFEST.iter().find(|entry| entry.path == path)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::BTreeMap;

    #[test]
    fn manifest_has_no_duplicate_paths() {
        let mut counts: BTreeMap<&str, u32> = BTreeMap::new();
        for entry in WIRING_MANIFEST {
            *counts.entry(entry.path).or_insert(0) += 1;
        }
        let duplicates: Vec<_> = counts.iter().filter(|(_, count)| **count > 1).collect();
        assert!(
            duplicates.is_empty(),
            "duplicate manifest paths: {duplicates:#?}"
        );
    }

    #[test]
    fn non_wired_entries_have_an_owner_and_a_reason() {
        for entry in WIRING_MANIFEST {
            if entry.status != WiringStatus::Wired {
                assert!(!entry.owner.is_empty(), "{} must name an owner", entry.path);
                assert!(
                    !entry.reason.is_empty(),
                    "{} must give a reason",
                    entry.path
                );
            }
        }
    }

    #[test]
    fn wired_entries_carry_no_diagnostic_behavior() {
        for entry in WIRING_MANIFEST {
            if entry.status == WiringStatus::Wired {
                assert_eq!(
                    entry.behavior,
                    WiringBehavior::None,
                    "{} is Wired but declares a non-None behavior",
                    entry.path
                );
            }
        }
    }

    #[test]
    fn rejected_status_always_pairs_with_rejected_behavior() {
        for entry in WIRING_MANIFEST {
            if entry.status == WiringStatus::Rejected {
                assert_eq!(entry.behavior, WiringBehavior::Rejected, "{}", entry.path);
            } else {
                assert_ne!(entry.behavior, WiringBehavior::Rejected, "{}", entry.path);
            }
        }
    }
}
